---
- name: Diagnostic - Verify EE Runtime Environment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check current executing user
      ansible.builtin.command: whoami
      register: whoami_out

    - name: List installed collections as runtime user
      ansible.builtin.command: ansible-galaxy collection list
      register: galaxy_out

    - name: Output Diagnostic Data
      ansible.builtin.debug:
        msg: 
          - "Running as user: {{ whoami_out.stdout }}"
          - "Collections visible to this user: "
          - "{{ galaxy_out.stdout_lines }}"
